### ISSUE TITLE
Error: ed_alloc no free edicts

### ISSUE THREAD

**Issue by fantasylidong** [himenekocn/NekoSpecials-L4D2#2]
您好，我用您的插件运行了一个绝境求生28特服务器，但是游玩过程经常会遇到实体过多导致炸服，目前用插件限制了实体数量上限才避免炸服，但是来提交一下issue，看您有空检查一下是不是多特插件这边的问题。
提供两个crash id。
https://crash.limetech.org/zm7cszsem2zf
https://crash.limetech.org/haxxkscdypvn

**Comment by himenekocn** [comment]
你是用的哪一个sourcemod版本呢

**Comment by fantasylidong** [comment]
用的原来你推荐的6826-1.11（今天改了6837了- -）
原来有错误日志的docker被我误删了，所以暂时提供不了其他日志，发完issue后做了几次测试没有复现，然后装了
https://forums.alliedmods.net/showthread.php?p=2728699 监控entity日志暂时没发现问题，过会我看一下自己的commit log看一下是不是其他插件问题，如果有复现，再过来reopen并添加更详细日志。
顺带一问，这插件除了改变特感还创建了什么实体吗？

**Comment by himenekocn** [comment]
创建特感就是增加实体，尽量将服务器其他插件的实体减少点看看
