### ISSUE TITLE
NekoServerName.smx未生效 nekocustom.cfg键值错误

### ISSUE THREAD

**Issue by TunArund** [himenekocn/NekoSpecials-L4D2#7]
![82a1d05d16ca6ff3c8192f3b2dac5356](https://github.com/user-attachments/assets/fa6cd92e-7f49-4f6e-841f-c120ae7491e7)
/home/steam/l4d2server/left4dead2/addons/sourcemod/logs/errors里没有相关报错
/home/steam/l4d2server/left4dead2/addons/sourcemod/data/nekocustom.cfg
```
"Settings"
{
	"KillHud_KillTankTitle"			"本次对Tank伤害"
	"KillHud_KillSpecialsTitle"		"击杀排行"
	"KillHud_FriendlyFireTitle"		"黑枪排行"
	"ServerNameFormat"	"TunArund多特{servernum}服[{specials}特{times}秒][重启:{restartcount}|路程:{flow}]{maptime}"
}
//以下为自定义服务器名字能加入的参数，根据个人选择加入
{servernum} 			//服务器数字 服务器端口后缀 27015 的 15 就是你的服务器数字
{specials} 			//目前多特数量，需要搭配Neko多特插件
{times} 			//目前多特刷新时间，需要搭配Neko多特插件
//{spawnmode} 			//目前多特刷特模式，需要搭配Neko多特插件
//{specialsmode} 		//目前多特特感模式，需要搭配Neko多特插件
//{gamedifficulty} 		//游戏难度
{restartcount} 		//失败重启次数
{flow} 				//当前玩家的路程
{maptime}			//目前地图时间，自带格式，例如[计时:2m:10s]
//{realplayernum}		//服务器在线真人人数，不包括特感
//{playernum}			//服务器在线人数含BOT，不包括特感
//{realaliveplayernum}	//服务器在线且存活真人人数，不包括特感
//{aliveplayernum}		//服务器存活真人人数，不包括特感
//{customtext}			//ServerName_CustomText这个Convar的内容
```
不知道填写格式如何，之前只删除开头的//，没用，怀疑是后面中文的问题，给注释了但是还有keyvalue错误

NekoServerName.smx之前可能与服务器中文名插件冲突
[l4d2_server_name.zip](https://github.com/user-attachments/files/17351416/l4d2_server_name.zip)
删了中文名插件后还是没用
![d49d3b116382a4109a90183511970170](https://github.com/user-attachments/assets/05456edf-4c05-4d5b-99af-b834b9dc0c2f)
顺带一提，如何默认打开特感投票？

**Comment by TunArund** [comment]
我发现如果之前装了**l4d2_nativevotes**插件
要删除并替换成仓库自带的，否则特感投票插件不会生效
附Neko[自带l4d2_nativevotes](https://github.com/himenekocn/NekoSpecials-L4D2/blob/NS7-SM1.11%2B/addons/sourcemod/plugins/l4d2_nativevote.smx)

**Comment by TunArund** [comment]
error日志里只有投票的报错
```
L 10/13/2024 - 00:14:39: SourceMod error session started
L 10/13/2024 - 00:14:39: Info (map "bt5") (file "/home/steam/l4d2server/left4dead2/addons/sourcemod/logs/errors_20241013.log")
L 10/13/2024 - 00:14:39: [SM] Plugin "l4d2_tankhp.smx" encountered error 23: Native detected error
L 10/13/2024 - 00:14:39: [SM] Invalid data handle 2 (error 7) passed during timer end with TIMER_DATA_HNDL_CLOSE
L 10/13/2024 - 00:14:39: [SM] Unable to call function "GetTankHealth" due to above error(s).
L 10/13/2024 - 00:16:14: [SM] Plugin "l4d2_tankhp.smx" encountered error 23: Native detected error
L 10/13/2024 - 00:16:14: [SM] Invalid data handle 4 (error 7) passed during timer end with TIMER_DATA_HNDL_CLOSE
L 10/13/2024 - 00:16:14: [SM] Unable to call function "GetTankHealth" due to above error(s).
L 10/13/2024 - 00:16:53: Error log file session closed.
L 10/13/2024 - 00:16:59: SourceMod error session started
L 10/13/2024 - 00:16:59: Info (map "c1m1_hotel") (file "/home/steam/l4d2server/left4dead2/addons/sourcemod/logs/errors_20241013.log")
L 10/13/2024 - 00:16:59: [SM] Plugin "l4d2_tankhp.smx" encountered error 23: Native detected error
L 10/13/2024 - 00:16:59: [SM] Invalid data handle 3 (error 1) passed during timer end with TIMER_DATA_HNDL_CLOSE
L 10/13/2024 - 00:16:59: [SM] Unable to call function "GetTankHealth" due to above error(s).
L 10/13/2024 - 00:27:30: Error log file session closed.
L 10/13/2024 - 01:37:00: SourceMod error session started
L 10/13/2024 - 01:37:00: Info (map "c1m1_hotel") (file "/home/steam/l4d2server/left4dead2/addons/sourcemod/logs/errors_20241013.log")
L 10/13/2024 - 01:37:00: [SM] Unable to load plugin "l4d2_player_status.smx": Native "GetWitchNumber" was not found
L 10/13/2024 - 01:37:00: [SM] Unable to load plugin "NekoVote.smx": Native "L4D2NativeVote.SetDisplayText" was not found
L 10/13/2024 - 01:37:00: [SM] Unable to load plugin "l4d2_tank_announce.smx": Native "GetWitchNumber" was not found
L 10/13/2024 - 01:37:31: Error log file session closed.
```

**Comment by himenekocn** [comment]
> 我发现如果之前装了**l4d2_nativevotes**插件 要删除并替换成仓库自带的，否则特感投票插件不会生效 附Neko[自带l4d2_nativevotes](https://github.com/himenekocn/NekoSpecials-L4D2/blob/NS7-SM1.11%2B/addons/sourcemod/plugins/l4d2_nativevote.smx)

7.10NS更新日志里面已经写了切换到FDXX的投票支持，是你没有看更新日志

**Comment by himenekocn** [comment]
> ![82a1d05d16ca6ff3c8192f3b2dac5356](https://private-user-images.githubusercontent.com/122089402/375985351-fa6cd92e-7f49-4f6e-841f-c120ae7491e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTYyNjcsIm5iZiI6MTczMTk5NTk2NywicGF0aCI6Ii8xMjIwODk0MDIvMzc1OTg1MzUxLWZhNmNkOTJlLTdmNDktNGY2ZS04NDFmLWMxMjBhZTc0OTFlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNTU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2RlODlmNmE2NjE2ZDcwYTMwMjVmNjg1NDhjMDU5OWUzMjA2YTUyNWI4MzczMzM4OGY3OTk5YjU4YjZkMDRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S2-Sa3zdVo9srA6dIjqTEs3uBmll-TFXFQL6c8E20o0) /home/steam/l4d2server/left4dead2/addons/sourcemod/logs/errors里没有相关报错 /home/steam/l4d2server/left4dead2/addons/sourcemod/data/nekocustom.cfg
> 
> ```
> "Settings"
> {
> 	"KillHud_KillTankTitle"			"本次对Tank伤害"
> 	"KillHud_KillSpecialsTitle"		"击杀排行"
> 	"KillHud_FriendlyFireTitle"		"黑枪排行"
> 	"ServerNameFormat"	"TunArund多特{servernum}服[{specials}特{times}秒][重启:{restartcount}|路程:{flow}]{maptime}"
> }
> //以下为自定义服务器名字能加入的参数，根据个人选择加入
> {servernum} 			//服务器数字 服务器端口后缀 27015 的 15 就是你的服务器数字
> {specials} 			//目前多特数量，需要搭配Neko多特插件
> {times} 			//目前多特刷新时间，需要搭配Neko多特插件
> //{spawnmode} 			//目前多特刷特模式，需要搭配Neko多特插件
> //{specialsmode} 		//目前多特特感模式，需要搭配Neko多特插件
> //{gamedifficulty} 		//游戏难度
> {restartcount} 		//失败重启次数
> {flow} 				//当前玩家的路程
> {maptime}			//目前地图时间，自带格式，例如[计时:2m:10s]
> //{realplayernum}		//服务器在线真人人数，不包括特感
> //{playernum}			//服务器在线人数含BOT，不包括特感
> //{realaliveplayernum}	//服务器在线且存活真人人数，不包括特感
> //{aliveplayernum}		//服务器存活真人人数，不包括特感
> //{customtext}			//ServerName_CustomText这个Convar的内容
> ```
> 
> 不知道填写格式如何，之前只删除开头的//，没用，怀疑是后面中文的问题，给注释了但是还有keyvalue错误
> 
> NekoServerName.smx之前可能与服务器中文名插件冲突 [l4d2_server_name.zip](https://github.com/user-attachments/files/17351416/l4d2_server_name.zip) 删了中文名插件后还是没用 ![d49d3b116382a4109a90183511970170](https://private-user-images.githubusercontent.com/122089402/375985440-05456edf-4c05-4d5b-99af-b834b9dc0c2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTYyNjcsIm5iZiI6MTczMTk5NTk2NywicGF0aCI6Ii8xMjIwODk0MDIvMzc1OTg1NDQwLTA1NDU2ZWRmLTRjMDUtNGQ1Yi05OWFmLWI4MzRiOWRjMGMyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNTU5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjU5NTJiZGJhNWJmM2FjNGUwZDQ0MzIxNzYzNGYzZGNlZjY5YTM3ZDA5M2ZkM2U1OTJmZDY1MjFiOTRiNzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J5_BfaD5NqrdD3hwMREGkp5SfKf5hcKD7uazJ8NXPrA) 顺带一提，如何默认打开特感投票？

这个是你文件编码出问题导致，检查是否是UTF8
